// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
//import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCZKAQoCk60sfA96Z6h1qCxNLwP-UJyOWs',
//     appId: '1:438191665824:web:595e4c408539b9a6250fc5',
//     messagingSenderId: '438191665824',
//     projectId: 'servicer-app-87829',
//     authDomain: 'servicer-app-87829.firebaseapp.com',
//     storageBucket: 'servicer-app-87829.appspot.com',
//     measurementId: 'G-ECZVD3YPR5',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCI_9rLwSJCE9GUhMMzf-fU88PqzSTTIUc',
//     appId: '1:438191665824:android:ce6e0aac7eba07ab250fc5',
//     messagingSenderId: '438191665824',
//     projectId: 'servicer-app-87829',
//     storageBucket: 'servicer-app-87829.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCundyKfTLS7C2wQsydY1g5ueUiXM3gYBI',
//     appId: '1:438191665824:ios:802e6a1fc5a64518250fc5',
//     messagingSenderId: '438191665824',
//     projectId: 'servicer-app-87829',
//     storageBucket: 'servicer-app-87829.appspot.com',
//     iosClientId: '438191665824-mhq60fur8d95m93a719da2ekv4efrmvf.apps.googleusercontent.com',
//     iosBundleId: 'com.paulpark.servicer',
//   );
// }
