/// Flutter icons MyFont
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFont
///      fonts:
///       - asset: fonts/MyFont.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFont {
  MyFont._();

  static const _kFontFam = 'MyFont';
  static const String? _kFontPkg = null;

  static const IconData cog_1 = IconData(0xf013, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xf015, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xf0c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_area = IconData(0xf1fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie = IconData(0xf200, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_line = IconData(0xf201, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
